internal/vpn.go
This was pointing at an invalid path and isn't needed for
initialization. Its not until fioctl *enables* wireguard that the
handler is needed and fioctl sets the handler for that.
=> vpn: Remove onchanged handler

go.mod, go.sum, internal/app.go, internal/ecies.go, internal/ecies_ethereum.go, internal/ecies_params_ethereum.go
This adds support to fioconfig for working with HSMs. It requires a patch to crytpo11:
https://github.com/ThalesIgnite/crypto11/pull/70
=> Add support for HSMs

go.mod, go.sum
We need this version to support the unquoted toml values used in
sota.toml
=> modules: Use patched go-toml library

internal/app.go, internal/app_test.go, internal/ecies.go, internal/vpn.go
This removes a long-lived session with the PKCS11 library and will
open/close for each check-in interval when the daemon is running.
=> app: Open/Close pkcs11 session between intervals

contrib/aktualizr-toml-update
Once fioconfig/fioctl take control of aklite configuration values, we
should assume it will own them. aklite now assumes that no entry for
"compose-apps" means run *all* apps. However, if fioconfig removes this
entry from the file it controls, the original versions would potentially
run apps the operator isn't wanting to run.
=> aklite callback: Disable defaults in sota.toml

contrib/factory-config-vpn
Depending on how fast the system performs the server and client
wireguard checks, it might end up getting the wrong result as the NM
connection removal is not done in a synchronous way (it can show up at
the nmcli conn output before fully removed).
Fix the race condition by just using the connection file instead when
checking if the vpn was previously set, as then we don't have to depend
on NM performing the full connection removal process.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
=> factory-config-vpn: check for connection state via nmconnection file

contrib/aktualizr-toml-update
/etc/sota/conf.d might not exist on the system at the time the handler
gets called, so make sure it gets created first, with the expected
permission (0700).
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
=> aktualizr-toml-update: make sure /etc/sota/conf.d/ exists

internal/app.go, internal/app_test.go, main.go
This allows a user to fioconfig in a more locked down mode so that
operators can't run arbitrary commands on a device.
=> Add "safe-handlers" capability

go.mod, internal/app.go, internal/app_test.go, internal/config.go, internal/recursive_delete_test.go, internal/vpn.go
The latest LmP is golang 1.17. Let's mark that for development to take advantages of some improvements in the language and prepare for the future deprecation of ioutil
=> Bump golang

go.mod, go.sum, internal/app.go, internal/app_test.go, internal/config.go, internal/ecies.go, internal/rotate.go, internal/rotate_config.go, internal/rotate_est.go, internal/rotate_finalize.go, internal/rotate_test.go, main.go
This is part one of a series of patches being introduced to support rotation of client certificates.
This first part does sets up all the pieces to perform a rotation. It's robust enough to be re-run after a failure and finish the operation.
It's missing a few things that I'll introduce in follow-up PRs including:
* emitting events to the device-gateway to track the progress of the rotation
* an on-change handler so that config changes can trigger this
* More robust retry logic for HTTP communications with the device-gateway
With this PR and my patched device-gateway, I'm able to rotate certificates in production.
=> Introduce certificate rotation logic

internal/rotate.go, internal/rotate_finalize.go
The resume logic was assuming when the given state existed that sota.toml would be updated. There's no guarantee for that. The full step is cheap to run and can be re-run w/o causing damage, so we should just simply re-run the step.
=> rotation: Fix bad resume logic

contrib/renew-client-cert, internal/app.go, internal/app_test.go, internal/rotate.go, main.go
This creates a flexible way for a certificate renew to be triggered via a configuration change. It can be tested with a conf file that looks like:
```
ESTSERVER=https://4a53f331-6f01-4694-8a97-af253d4d9b63.est.foundries.io:8443/.well-known/est
TIMESTAMP=1667240722
PKEYIDS=01,07
CERTIDS=03,09
```
=> rotation: Add on-change handler for fioctl

go.mod, go.sum, internal/current_target.go, internal/current_target_test.go, internal/http.go, internal/rotate.go, internal/rotate_events.go, internal/rotate_test.go
This change allows cert rotations to integrate with our device gateway's update events to produce something like:
```
$ fioctl devices updates og-qemu-hsm
ID                                        TIME                  VERSION  TARGET
--                                        ----                  -------  ------
certs-1668446396                          2022-11-14T17:19:58Z  282      intel-corei7-64-lmp-282
282-43ad1cd7-0228-431f-85b0-da5757ff5705  2022-11-14T17:19:44Z  282      intel-corei7-64-lmp-282
[doanac@xps15 fioconfig]$ fioctl devices updates og-qemu-hsm certs-1668446396
2022-11-14T17:19:56+00:00 : CertRotationStarted(intel-corei7-64-lmp-282) -> Succeed
2022-11-14T17:19:56+00:00 : Generate new certificate(intel-corei7-64-lmp-282) -> Succeed
2022-11-14T17:19:57+00:00 : Lock device …
```
=> rotation: Emit update events to device gateway

internal/http.go, internal/http_test.go
This should help make fioconfig a little more resilient to failures by handling HTTP errors that might succeed if we try again.
=> internal: Introduce HTTP retry logic

contrib/renew-client-cert, internal/app.go, internal/app_test.go
The `fioconfig renew-cert` command itself has retry logic. However, if that logic fails, fioconfig will carry along and never complete a rotation.
This change adds an even bigger retry loop around that process and will finally restart fioconfig if that fails. This will hopefully cause enough restarts that between systemd and fioconfig, things will finally get re-run to completion.
=> contrib: Add retries to renew-client-cert

contrib/aktualizr-toml-update
This will revert the change of commenting out it being managed by `fioconfig` when it is no longer being managed by `fioconfig`.
=> fix(trigger): Revert back when ommitting tag

internal/app.go, internal/app_test.go
The current logic has a bug that can more or less "brick" fioconfig:
* echo "not valid json" > /var/sota/config.encrypted
* daemon will not be able to process new config changes
=> Don't fail on corrupted config.encrypted file

internal/rotate.go, internal/rotate_config.go, internal/rotate_est.go, internal/rotate_events.go, internal/rotate_finalize.go, internal/rotate_lock.go, internal/rotate_test.go, internal/state.go, main.go
I need to re-use a major part of renew-cert for the renew-root logic. Trying to do this in a truly reusable way comes with some pitfalls. This one uses generics.
It looks more nuanced, but comes with a more clear interface. Besides, it is more Golang-ish.
=> Refactor: extract the generic state machine into base types

contrib/aktualizr-toml-update
We've tried to maintain this clever way of commenting out config items managed by fioctl/fioconfig. However, its never been easy. With the introduction of change:
https://github.com/foundriesio/fioconfig/commit/7319b01c90b99847782f07f28734f90159146093
We no longer get the exact name of sota.toml. We never really knew this for a fact but this change made it a reality. Rather than guessing about the TOML file, lets not do the comments - its not hard to tell: if there's a z-50-fioctl.toml file - then we are managing it.
=> contrib: Simplify aktualizr config handler

internal/rotate_config.go, internal/rotate_finalize.go
This is an edge case as the client cert rotation is usually triggered via a config.
But, in some cases a user might want to run renew-client-cert manually.
If there is no config.encrypted file, this would fail.
=> Fix: client rotation fails when there is no config

contrib/aktualizr-toml-update
This facilitates the use of fioconfig when a custom OTA solution that requires the aklite daemon to be stopped is in use.
=> contrib: Do not restart aklite service if it is not enabled

internal/app.go, internal/config.go, internal/ecies.go, internal/http_test.go, internal/rotate_config.go, internal/rotate_est.go, internal/rotate_events.go, internal/rotate_finalize.go, internal/rotate_lock.go, internal/rotate_test.go, internal/state.go, main.go, sotatoml/app_config.go, sotatoml/app_config_test.go, sotatoml/safewrite.go, transport/http.go, transport/http_client.go, transport/tls.go, transport/tls_no_pkcs11.go, transport/tls_pkcs11.go
This allows config toml parsing and device gateway communication features to be used in other golang tools, like the experimental update client hosted at https://github.com/foundriesio/fiotuf
---
@doanac I haven't changed your 3 patches, just rebased them and added a few more changes of my own as separate patches. Let us know if there anything you believe is not ready for merge yet.
=> Move transport and sota config logic to packages

transport/http.go
The remote actions feature needed two things:
* access to the HttpDo function
* ability to upload binary data and not just JSON marshalled data
While digging around I cleaned some warnings linters noticed.
=> Changes to transport module to help with remote actions

internal/ecies.go, internal/ecies_no_pkcs11.go, internal/ecies_pkcs11.go, internal/rotate_est.go, internal/state.go
The tag works properly for applications only using the transport module, but fioconfig itself can't compile with that option set. This isn't required, but it does clean up our dependencies on this code and how we interface with it.
=> Get the disable_pkcs11 tag working

sotatoml/app_config.go, transport/http_client.go
- Specify .toml file path in the error context if parsing error occurs.
- Don't exit if an error occurs during the http client creation, return the error instead.
=> Tiny improvements

transport/http.go
If an external utility uses this package then it makes sense to allow the utility to set the user-agent header value, as well as content type. If a client doesn't set those headers then the default one are set.
=> http: Allow client to set user agent and content type
